name: Deploy SvelteKit Site

on:
  push:
    branches: [main]  # or 'master' if that's your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: husted-dot-dev  # 👈 run all commands from inside this folder

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build site
        run: pnpm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: husted-dot-dev/build
          cname: husted.dev
